### === START User ===
@userBaseUrl = http://localhost:3000/users
@userId = 12345678-1234-1234-1234-123456789012

### Create User
POST {{userBaseUrl}}
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123",
  "name": "Sample name"
}

### Get all users
GET {{userBaseUrl}}

### Get User by ID
GET {{userBaseUrl}}/{{userId}}

### Update User
PUT {{userBaseUrl}}/{{userId}}
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123",
  "name": "Sample name"
}

### Delete User
DELETE {{userBaseUrl}}/{{userId}}

### === END User ===
